### PR TITLE
Add link for the Scrimba online course

### PR DESCRIPTION
**Pull request by PedroCristo**
I have added a link to a platform where I have been learning and improving my coding skills. It's one of the most advanced screens I have tried as we can watch videos but also change the code inside the video itself.

# Link
https://scrimba.com/

### CODE REVIEW

**Review by NiallJoeMaher — CHANGES_REQUESTED** [review]
Hey! Could you check your linting tools since this changes most of the formatting?

For one item being added, I'd only expect one line change instead of 45. 🦾

Could you make sure you are just updating the lines you want to add? 

Looks like great additions. Thanks!!! ❤️

**Comment by PedroCristo** [comment]
It appears that Gitop had a default configuration causing changes to the table format when I was saving the file while I was working with it. I think is done now! Thanks.

**Review by NiallJoeMaher — APPROVED** [review]
Wooo thanks! 🥳

**Comment by PedroCristo** [comment]
You are very welcome!! @NiallJoeMaher

**Pull request merged**
